### ISSUE TITLE
zipped package does not include all needed libraries like win32api ...

### ISSUE THREAD

**Issue by ClaudiaFrank** [bitagoras/PyPadPlusPlus#1]
If an user doesn't have a local python installation, pyPadPlusPlus dies with ImportError.
In order to prevent dependencies issues you might consider using ctypes directly.

Edit: this is an 32bit package, running on a 64bit platform with 64bit python doesn't work, 
so I guess implementing the win32 calls via ctypes is the easiest way to make it 32/64 bit compliant.

Edit: quick test with using ctypes instead of win32api ... worked.
Here what I've changed in __init__.py

    # import win32api, win32con, win32gui
    
    from ctypes import windll
    GetForegroundWindow = windll.user32.GetForegroundWindow
    GetParent = windll.user32.GetParent
    GetWindowRect = windll.user32.GetWindowRect
    WindowFromPoint = windll.user32.WindowFromPoint
    GetCursorPos = windll.user32.GetCursorPos
    GetKeyState = windll.user32.GetKeyState
    VK_MBUTTON = 4

and calling the respective lines without the win32... prefixes like

        # self.windowHandle = win32gui.GetForegroundWindow()
        self.windowHandle = GetForegroundWindow()

**Comment by bitagoras** [comment]
Oh ok, I did not realize that these modules were imported from my local Python installation. Thank you for this suggestion. Your solution works perfect. Only two of the functions were slightly different in the calling structure compared to the old functions, since they require another ctype variable for a by-referece return value.

I just discovered another problem with the internal Python mode. I use relativ paths in the config of Python Script. This seems to be a problem, since the first execution changes the working directory to that of the current file. Then Python Script then can't find the scripts any more (pyPadExecute.py). I have to think about a solution.

**Comment by ClaudiaFrank** [comment]
As far as I remember, the concept of relative path usage covers only "user" but not "machine" scripts.
Maybe the easiest would be switching the cwd back and forth or maybe better provide an unique path
variable to the threads
Or you are using startup.py to find out where npp is located, then modify PythonScriptStartup.cnf
entries accordingly and ask the user to restart npp. Should be necessary only for the first time as long
as the user doesn't move npp into another directory.
Not really satisfying I guess.

**Comment by bitagoras** [comment]
Great! The solution with the user scripts works perfect. I just I misunderstood the concept of Python Script concerning the user script folder. It's so easy to find a solution with the help of an expert. Thank you again!
